# Generated by Django 5.2.8 on 2025-11-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='video_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
