# Generated by Django 5.2.8 on 2025-11-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_conversiontask_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='logs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
