# Generated by Django 5.2.8 on 2025-11-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_conversiontask_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversiontask',
            name='timing_map',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
